# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'chromedriver-helper', '~> 1.1'
gem 'rspec', '~> 3.7'
gem 'watir', '~> 6.10', '>= 6.10.2'
